Check files development
Mbed-TLS/TF-PSA-Crypto pull request #133
Opened 2024-12-27 10:41 UTC by Harry-Ramsey

## Description
Enable check_files.py for TF-PSA-Crypto. Closes #51.

## PR checklist

Please remove the segment/s on either side of the | symbol as appropriate, and add any relevant link/s to the end of the line.
If the provided content is part of the present PR remove the # symbol.

- [x] **changelog** not required because: testing enhancement.
- [x] **framework PR** provided Mbed-TLS/mbedtls-framework# | not required
- [x] **mbedtls PR** not required.
- **tests** provided.

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/TF-PSA-Crypto/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

Help make review efficient:
* Multiple simple commits
  - please structure your PR into a series of small commits, each of which does one thing
* Avoid force-push
  - please do not force-push to update your PR - just add new commit(s)
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for more details about the review process.

2025-01-10 11:44 UTC, ronald-cron-arm submitted a review, later dismissed
LGTM

2025-01-13 08:47 UTC, valeriosetti commented
It seems to me that the `framework` reference is not correct. It's pointing to `2e1d022f9038358e0472b0deaed65a0ed3374912` but it should instead point to https://github.com/Mbed-TLS/mbedtls-framework/pull/109/commits/2988e24290bcb6a7137d943fe643431406057282. Isn't it?

I know that this PR is going to be updated anyway once the framework PR is merged, but for the sake of CI testing I think it would be better to test the proper version.

2025-01-13 08:53 UTC, Harry-Ramsey commented
Yes, good spot. I shall update the framework pointer now. CI should continue passing with any luck :)

2025-01-13 10:34 UTC, valeriosetti requested changes

2025-01-13 10:34 UTC, valeriosetti commented on tests/scripts/components-basic-checks.sh
> +component_tf_psa_crypto_check_files () {
The originating issue says we need 2 new components: `component_tf_psa_crypto_check_files` (added here) and `component_tf_psa_crypto_check_python_files` which I cannot find anywhere in the repo. Just to be sure, was it intentional to skip the 2nd?

2025-01-13 10:47 UTC, Harry-Ramsey commented on tests/scripts/components-basic-checks.sh
> +component_tf_psa_crypto_check_files () {
Ah, it was edited since I last saw it. Let me add a new component for `check_python_files`.

2025-01-13 13:31 UTC, Harry-Ramsey commented on tests/scripts/components-basic-checks.sh
> +    ./framework/scripts/check-python-files.sh
Sorry forgot to edit that line. Both are the same but ideally for maintainability I should have used `$FRAMEWORK`.

2025-01-13 13:36 UTC, valeriosetti approved these changes
Thanks for addressing my comment. LGTM :)

2025-01-15 10:17 UTC, ronald-cron-arm approved these changes
LGTM

2025-01-15 14:48 UTC, ronald-cron-arm approved these changes
LGTM

2025-01-15 15:24 UTC, valeriosetti approved these changes

2025-01-15 19:30 UTC, merged