Add basic miscellaneous components to TF-PSA-Crypto
Mbed-TLS/TF-PSA-Crypto pull request #134
Opened 2024-12-27 11:11 UTC by Harry-Ramsey

This commit adds basic miscellaneous components to TF-PSA-Crypto. Closes #53.

## PR checklist

Please remove the segment/s on either side of the | symbol as appropriate, and add any relevant link/s to the end of the line.
If the provided content is part of the present PR remove the # symbol.

- [x] **changelog** not required because: testing enhancement.
- [x] **framework PR** not required.
- [x] **mbedtls PR** not required.
- **tests**  provided | not required because: 

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/TF-PSA-Crypto/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

Help make review efficient:
* Multiple simple commits
  - please structure your PR into a series of small commits, each of which does one thing
* Avoid force-push
  - please do not force-push to update your PR - just add new commit(s)
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for more details about the review process.

2025-01-13 08:27 UTC, ronald-cron-arm requested changes
This looks good to me but I think I missed in the first place the component `check_test_helpers` (now in .https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/53 description). Please add it as well.

2025-01-13 09:43 UTC, Harry-Ramsey commented
> This looks good to me but I think I missed in the first place the component `check_test_helpers` (now in .#53 description). Please add it as well.

Added `check_test_helpers now`.

2025-01-17 08:56 UTC, ronald-cron-arm requested changes
This looks mostly good to me, thanks. Two things I'd like to improve.

2025-01-17 08:56 UTC, ronald-cron-arm commented on tests/scripts/components-basic-checks.sh
> +    $FRAMEWORK/scripts/check_test_cases.py -q $opt
```suggestion
    $FRAMEWORK/scripts/check_test_cases.py $opt
```
I can see it is as in the mbedtls one but this seems not correct.

2025-01-17 08:56 UTC, ronald-cron-arm commented on tests/scripts/components-basic-checks.sh
> +component_tf_psa_crypto_check_test_dependencies () {
I think we can just remove the corresponding one in mbedtls.

2025-01-17 09:17 UTC, Harry-Ramsey commented on tests/scripts/components-basic-checks.sh
> +    $FRAMEWORK/scripts/check_test_cases.py -q $opt
Fixed.

2025-01-17 09:22 UTC, ronald-cron-arm submitted a review, later dismissed
LGTM

2025-01-17 09:23 UTC, Harry-Ramsey commented on tests/scripts/components-basic-checks.sh
> +component_tf_psa_crypto_check_test_dependencies () {
Created: https://github.com/Mbed-TLS/mbedtls/pull/9914

2025-01-17 13:11 UTC, valeriosetti approved these changes

2025-01-17 15:57 UTC, valeriosetti approved these changes

2025-01-17 17:14 UTC, ronald-cron-arm approved these changes
LGTM

2025-01-17 20:19 UTC, merged