Add PSA_CRYPTO_DEPRECATED_REMOVED/WARNING config options from Mbed TLS
Mbed-TLS/TF-PSA-Crypto pull request #95
Opened 2023-12-12 17:48 UTC by tom-daubney-arm

Fixes #54

2023-12-21 19:17 UTC, gabor-mezei-arm requested changes
Only a typo found, otherwise LGTM.

2023-12-21 19:17 UTC, gabor-mezei-arm commented on drivers/builtin/include/mbedtls/config_adjust_mbedtls_from_tf_psa_crypto.h
> +
No need for extra newlines.

2024-01-03 13:06 UTC, gabor-mezei-arm approved these changes
LGTM

2025-01-02 09:50 UTC, ronald-cron-arm commented
Closing as #54 is outdated now.

2025-01-02 09:50 UTC, closed without merging